### ISSUE TITLE
Image Switch

### ISSUE THREAD

**Issue by madsdura** [Maxzilla60/AC-Lister#1275]
Hi! When I click on Sylvana, I am presented with an image of Sylvia, however when I click on Sylvia, there is only the under-construction image! Just wanted to let you know! I don't know if you are still maintaining the site, but I found it today and love it! Thank you so much for putting it all together and preserving purple-pixel's amazing artwork, since they appear to have deleted all their socials. :( I've started to attempt making my own icons in their style to fill in the gaps, but it's not nearly as good. Fortunately, I'm the only one who will ever see it, and they will be so tiny on my little amiibo coins that I doubt even I will be able to tell! I also wanted to let you know that I saw on RedBubble there is an image for Audie, but there is no image for Audie on the database. Thank you!!!

**Comment by Maxzilla60** [comment]
Heya! Thanks for letting me know about this bug, will definitely be fixing it! 👍

I did indeed notice purple-pixel's been deleting their socials, I'll update that as well.

As for their newer art they've been making, I'll consider adding it to the website. No promises.

I'm very happy to hear people still make use of this old project of mine! I appreciate the heads up! 💛
